---
- hosts: all

  # Here we define our tasks
  tasks:
    # This is the first task
    - name: List files in a directory
      # As learned before this is the command module
      # This command will list files in the home directory
      command: ls ~

      # register is used whenever we wish to save the output
      # In this case it will be saved to a variable called 'files'
      register: files

    # This is the second tasks
    # In this case the tasks will run in the declared sequence
    - name: Print the list of files
      # Using the builtin debug module
      # The debug will print out our files list
      # ** We need to use `stdout_lines` for that
      debug:
        msg: "{{ files.files }}"

---
- name: List files in a directory

  hosts: linux-server-1
  tasks:
    - name: Find files
      find:
        # Set the path as parameter to the playbook
        # try different options for the path value as we
        # explained above
        paths: <path_to_directory>
        file_type: file
      register: files_to_print

    # Print the files list
    - name: Print files
      debug:
        msg: "{{ item.path }}"
      # with_items?
      # What is it and why do we use it here
      with_items: "{{ files_to_print.files }}"
